[package]
name = "next-release"
version = "0.1.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = { version = "0.9.11" }
toml_edit = { version = "0.24.0" }
semver = { version = "1.0.27" }
